img_HSV.auto_white: 4844
img_HSV.exposure: 24
img_HSV.highH: 43
img_HSV.highS: 229
img_HSV.highV: 82
img_HSV.lowH: 78
img_HSV.lowS: 145
img_HSV.lowV: 13
img_displayFilteredContours.contoursOpeningKernelSize: 5
